const topics = [
  {id:'present-tenses',level:'A1',icon:'01',title:'Hiện tại đơn & tiếp diễn',desc:'Thói quen, sự thật và hành động đang diễn ra.',color:'violet',time:12,
   intro:'Hai thì hiện tại trả lời hai câu hỏi khác nhau: “Điều này có thường xuyên xảy ra không?” và “Điều này có đang xảy ra ngay lúc nói không?”',
   formulas:[['Hiện tại đơn','S + V(s/es)','She works from home.'],['Hiện tại tiếp diễn','S + am/is/are + V-ing','She is working from home today.']],
   uses:[['Thói quen / lịch cố định','I check my email every morning.'],['Sự thật, trạng thái','Water boils at 100°C.'],['Đang xảy ra lúc nói','They are having a meeting now.'],['Tình huống tạm thời','I am staying with my sister this week.']],
   signals:['always','usually','every day','often','now','right now','at the moment','this week'],
   mistake:['I am knowing the answer.','I know the answer.','Các động từ trạng thái như know, like, need thường không dùng ở dạng tiếp diễn.']},
  {id:'past-tenses',level:'A2',icon:'02',title:'Quá khứ đơn & tiếp diễn',desc:'Kể lại sự kiện và đặt bối cảnh trong quá khứ.',color:'blue',time:14,
   intro:'Quá khứ tiếp diễn tạo “phông nền”; quá khứ đơn kể sự kiện chính chen vào hoặc đã hoàn tất.',
   formulas:[['Quá khứ đơn','S + V2/ed','I called the client yesterday.'],['Quá khứ tiếp diễn','S + was/were + V-ing','I was driving when she called.']],
   uses:[['Hành động đã kết thúc','We finished the report last night.'],['Chuỗi sự kiện','He arrived, sat down and opened his laptop.'],['Hành động đang diễn ra','At 8 p.m., I was still working.'],['Một việc chen ngang','I was presenting when the screen went black.']],
   signals:['yesterday','last week','ago','in 2024','while','when','at 8 p.m.'],mistake:['While I worked, he called.','While I was working, he called.','Sau “while”, thường dùng quá khứ tiếp diễn để diễn tả hành động nền.']},
  {id:'future',level:'A2',icon:'03',title:'Will, be going to & hiện tại tiếp diễn',desc:'Dự đoán, dự định và kế hoạch đã sắp xếp.',color:'orange',time:13,
   intro:'Tiếng Anh không chỉ có một cách nói tương lai. Lựa chọn cấu trúc phụ thuộc vào mức độ chắc chắn và thời điểm ra quyết định.',
   formulas:[['Quyết định tức thời','S + will + V','I’ll answer the phone.'],['Dự định / bằng chứng','S + be going to + V','It is going to rain.'],['Kế hoạch đã chốt','S + be + V-ing','I am meeting Lan at 3.']],
   uses:[['Will','Lời hứa, đề nghị, quyết định ngay lúc nói.'],['Going to','Ý định có trước hoặc dự đoán có bằng chứng.'],['Present continuous','Cuộc hẹn đã sắp xếp thời gian, địa điểm.']],signals:['I think','probably','look!','plan to','tomorrow','at 3 p.m.'],mistake:['I will meeting her tomorrow.','I will meet her tomorrow.','Sau will luôn dùng động từ nguyên mẫu không “to”.']},
  {id:'present-perfect',level:'B1',icon:'04',title:'Hiện tại hoàn thành',desc:'Kết nối trải nghiệm quá khứ với hiện tại.',color:'green',time:15,
   intro:'Dùng khi thời điểm không quan trọng hoặc kết quả quá khứ vẫn liên quan tới hiện tại.',
   formulas:[['Khẳng định','S + have/has + V3','I have finished the report.'],['Phủ định','S + have/has not + V3','She has not replied yet.'],['Câu hỏi','Have/Has + S + V3?','Have you ever worked abroad?']],
   uses:[['Trải nghiệm','I have visited Singapore twice.'],['Kết quả hiện tại','She has lost her key.'],['Khoảng thời gian chưa kết thúc','We have had three meetings today.'],['Bắt đầu trong quá khứ, còn tiếp tục','I have worked here for two years.']],signals:['already','yet','just','ever','never','since','for','so far'],mistake:['I have seen him yesterday.','I saw him yesterday.','Có mốc quá khứ đã kết thúc (yesterday), dùng quá khứ đơn.']},
  {id:'present-perfect-continuous',level:'B1',icon:'05',title:'Hiện tại hoàn thành tiếp diễn',desc:'Nhấn mạnh quá trình bắt đầu trước đây và còn tiếp tục.',color:'teal',time:15,
   intro:'Hãy nghĩ đến một hoạt động đã chạy được bao lâu tới hiện tại. Thì này nhấn mạnh quá trình hoặc dấu hiệu vừa thấy, không chỉ kết quả.',
   formulas:[['Khẳng định','S + have/has been + V-ing','I have been studying for two hours.'],['Phủ định','S + have/has not been + V-ing','She has not been sleeping well.'],['Câu hỏi','Have/Has + S + been + V-ing?','Have you been waiting long?']],
   uses:[['Còn đang tiếp tục','We have been working since 8 a.m.'],['Vừa dừng, có bằng chứng','Your hands are dirty. Have you been gardening?'],['Nhấn mạnh thời lượng','He has been learning English for six months.'],['Hoạt động lặp lại gần đây','They have been calling me all morning.']],
   signals:['for','since','all day','lately','recently','how long'],mistake:['I am studying for three hours.','I have been studying for three hours.','Một hoạt động bắt đầu trong quá khứ và kéo dài tới hiện tại cần have/has been + V-ing.']},
  {id:'past-perfect',level:'B1',icon:'06',title:'Quá khứ hoàn thành',desc:'Hành động đã hoàn tất trước một mốc quá khứ khác.',color:'violet',time:14,
   intro:'Khi kể hai việc trong quá khứ, dùng quá khứ hoàn thành cho việc xảy ra trước để thứ tự câu chuyện thật rõ ràng.',
   formulas:[['Khẳng định','S + had + V3','The train had left before we arrived.'],['Phủ định','S + had not + V3','I had not seen the email before the meeting.'],['Câu hỏi','Had + S + V3?','Had she finished when you called?']],
   uses:[['Việc xảy ra trước','The film had started when we entered.'],['Nguyên nhân trong quá khứ','He was tired because he had slept badly.'],['Kinh nghiệm trước một mốc','She had never flown before that trip.'],['Câu gián tiếp','He said he had completed the task.']],
   signals:['before','after','by the time','already','never','when'],mistake:['When I arrived, they left already.','When I arrived, they had already left.','Việc rời đi xảy ra trước lúc tôi đến nên dùng had + V3.']},
  {id:'past-perfect-continuous',level:'B1',icon:'07',title:'Quá khứ hoàn thành tiếp diễn',desc:'Nhấn mạnh quá trình kéo dài trước một thời điểm quá khứ.',color:'blue',time:16,
   intro:'Thì này trả lời “đã làm việc đó được bao lâu trước lúc chuyện khác xảy ra?” và thường giải thích một kết quả nhìn thấy trong quá khứ.',
   formulas:[['Khẳng định','S + had been + V-ing','I had been working for hours before lunch.'],['Phủ định','S + had not been + V-ing','She had not been feeling well.'],['Câu hỏi','Had + S + been + V-ing?','Had it been raining all night?']],
   uses:[['Kéo dài trước mốc quá khứ','They had been waiting for an hour when the bus came.'],['Giải thích kết quả quá khứ','The road was wet because it had been raining.'],['Nhấn mạnh quá trình','I had been preparing all week before the exam.'],['Hoạt động tạm thời trước đó','He had been staying with a friend before he moved.']],
   signals:['for','since','before','when','all day','how long'],mistake:['I had been knowing her for years.','I had known her for years.','Động từ trạng thái như know thường không dùng ở dạng tiếp diễn.']},
  {id:'future-continuous',level:'B1',icon:'08',title:'Tương lai tiếp diễn',desc:'Hành động sẽ đang diễn ra tại một thời điểm tương lai.',color:'orange',time:13,
   intro:'Hãy đặt mình vào một thời điểm trong tương lai và mô tả việc đang diễn ra tại đúng thời điểm đó.',
   formulas:[['Khẳng định','S + will be + V-ing','I will be presenting at 10 a.m.'],['Phủ định','S + will not be + V-ing','We will not be working tomorrow evening.'],['Câu hỏi','Will + S + be + V-ing?','Will you be using the meeting room?']],
   uses:[['Đang diễn ra ở tương lai','This time tomorrow, I will be flying to Seoul.'],['Kế hoạch diễn ra tự nhiên','I will be meeting the team next week.'],['Hỏi kế hoạch lịch sự','Will you be joining us for lunch?'],['Hai việc song song','She will be studying while I am working.']],
   signals:['this time tomorrow','at 8 p.m. tomorrow','next week','when'],mistake:['At 9 tomorrow, I will work.','At 9 tomorrow, I will be working.','Nhấn mạnh hành động đang diễn ra tại một mốc tương lai: will be + V-ing.']},
  {id:'future-perfect',level:'B1',icon:'09',title:'Tương lai hoàn thành',desc:'Hành động sẽ hoàn tất trước một hạn trong tương lai.',color:'green',time:14,
   intro:'Dùng khi có một “deadline” tương lai và bạn muốn nói việc gì sẽ hoàn thành trước hoặc chậm nhất vào mốc đó.',
   formulas:[['Khẳng định','S + will have + V3','I will have finished by Friday.'],['Phủ định','S + will not have + V3','They will not have arrived by six.'],['Câu hỏi','Will + S + have + V3?','Will you have completed it by noon?']],
   uses:[['Hoàn tất trước hạn','She will have sent the report by 5 p.m.'],['Dự đoán thành tựu','By 2030, they will have built the bridge.'],['Tính tổng tới tương lai','Next month, I will have worked here for a year.'],['Kiểm tra tiến độ','Will you have read it before the meeting?']],
   signals:['by','by the time','before','by then','by next year'],mistake:['I will finish it by you arrive.','I will have finished it by the time you arrive.','Sau by the time dùng hiện tại đơn; hành động hoàn tất dùng will have + V3.']},
  {id:'future-perfect-continuous',level:'B1',icon:'10',title:'Tương lai hoàn thành tiếp diễn',desc:'Nhấn mạnh thời lượng kéo dài tới một mốc tương lai.',color:'red',time:16,
   intro:'Đây là thì ít dùng hơn nhưng rất rõ nghĩa: tới một mốc tương lai, hoạt động sẽ đã kéo dài được bao lâu.',
   formulas:[['Khẳng định','S + will have been + V-ing','By June, I will have been working here for two years.'],['Phủ định','S + will not have been + V-ing','He will not have been studying for long.'],['Câu hỏi','Will + S + have been + V-ing?','Will they have been travelling for a month?']],
   uses:[['Thời lượng tới tương lai','At noon, she will have been driving for five hours.'],['Quá trình liên tục','By 2028, we will have been living here for a decade.'],['Giải thích kết quả tương lai','He will be tired because he will have been working all night.'],['Nhấn mạnh hoạt động','Next week, I will have been training for six months.']],
   signals:['for','by','by the time','when','by next month'],mistake:['By May, I will be working here for ten years.','By May, I will have been working here for ten years.','Khi nhấn mạnh khoảng thời gian kéo dài tới mốc tương lai, dùng will have been + V-ing.']},
  {id:'modals',level:'A2',icon:'11',title:'Modal verbs',desc:'Can, could, should, must, have to trong giao tiếp.',color:'pink',time:12,
   intro:'Modal verbs giúp thể hiện khả năng, lời khuyên, sự bắt buộc và mức độ lịch sự.',
   formulas:[['Công thức chung','S + modal + V nguyên mẫu','You should check it again.'],['Phủ định','S + modal + not + V','You must not share this file.'],['Câu hỏi','Modal + S + V?','Could you help me?']],
   uses:[['can / could','Khả năng; could lịch sự hơn khi nhờ vả.'],['should','Lời khuyên, điều nên làm.'],['must / have to','Sự bắt buộc; must thường từ người nói.'],['mustn’t','Cấm làm, không phải “không cần”.']],signals:['can','could','should','must','have to','may','might'],mistake:['She can to speak English.','She can speak English.','Sau modal verb dùng động từ nguyên mẫu, không có “to”.']},
  {id:'articles',level:'A1',icon:'12',title:'Mạo từ a, an & the',desc:'Nói về một đối tượng chung hay cụ thể.',color:'yellow',time:10,
   intro:'A/an giới thiệu một danh từ đếm được chưa xác định; the chỉ đối tượng người nghe đã biết hoặc là duy nhất.',
   formulas:[['a / an','a/an + danh từ số ít','I need a charger.'],['the','the + danh từ xác định','The charger is on my desk.'],['Không mạo từ','Ø + danh từ chung','Coffee helps me focus.']],
   uses:[['a / an','Một trong nhiều; nhắc đến lần đầu.'],['the','Đã nhắc, đã xác định, hoặc duy nhất.'],['a hay an theo âm','an hour nhưng a university.'],['Không mạo từ','Danh từ số nhiều/không đếm được khi nói chung.']],signals:['first mention','specific','only one','in general'],mistake:['She is an university student.','She is a university student.','University bắt đầu bằng âm /j/, nên dùng “a”.']},
  {id:'conditionals',level:'B1',icon:'13',title:'Câu điều kiện 0, 1 & 2',desc:'Sự thật, khả năng thật và tình huống giả định.',color:'teal',time:16,
   intro:'Loại câu điều kiện thể hiện mức độ thực tế: luôn đúng, có thể xảy ra, hay chỉ là giả định.',
   formulas:[['Loại 0','If + hiện tại, hiện tại','If you heat ice, it melts.'],['Loại 1','If + hiện tại, will + V','If it rains, we will stay home.'],['Loại 2','If + quá khứ, would + V','If I had more time, I would travel.']],
   uses:[['Loại 0','Sự thật, quy luật, hướng dẫn.'],['Loại 1','Khả năng có thật ở hiện tại/tương lai.'],['Loại 2','Giả định khó hoặc không có thật.'],['Dấu phẩy','Dùng dấu phẩy khi mệnh đề if đứng trước.']],signals:['if','unless','when','would','will'],mistake:['If it will rain, we will cancel.','If it rains, we will cancel.','Trong mệnh đề if loại 1 không dùng will.']},
  {id:'passive',level:'B1',icon:'14',title:'Câu bị động',desc:'Tập trung vào hành động, kết quả hoặc đối tượng.',color:'red',time:15,
   intro:'Dùng bị động khi người thực hiện không quan trọng, không biết hoặc khi muốn nhấn mạnh kết quả.',
   formulas:[['Hiện tại','S + am/is/are + V3','The files are stored online.'],['Quá khứ','S + was/were + V3','The email was sent yesterday.'],['Modal','S + modal + be + V3','This must be completed today.']],
   uses:[['Không biết tác nhân','My laptop was stolen.'],['Quy trình','The data is checked automatically.'],['Nhấn mạnh kết quả','The project has been approved.'],['Tác nhân cần thiết','The design was created by Mai.']],signals:['be + V3','by','is made','was sent','must be'],mistake:['The report sent yesterday.','The report was sent yesterday.','Bị động luôn cần một dạng của “be” trước quá khứ phân từ.']}
];

const questions = [
  {q:'Lan usually ___ from home on Fridays.',o:['work','works','is working'],a:1,e:'“Usually” diễn tả thói quen. Chủ ngữ Lan (she) nên động từ thêm -s.'},
  {q:'Please call later. We ___ a meeting right now.',o:['have','had','are having'],a:2,e:'“Right now” là dấu hiệu của hiện tại tiếp diễn: are having.'},
  {q:'I ___ the client when the internet stopped working.',o:['was calling','called','am calling'],a:0,e:'Hành động gọi đang diễn ra thì một sự kiện khác chen vào.'},
  {q:'Look at those clouds! It ___ rain.',o:['will','is going to','is raining every day'],a:1,e:'Có bằng chứng hiện tại (mây đen), dùng be going to để dự đoán.'},
  {q:'She has worked here ___ three years.',o:['since','for','ago'],a:1,e:'“For” đi với một khoảng thời gian; “since” đi với mốc bắt đầu.'},
  {q:'You ___ share your password with anyone.',o:['mustn’t','don’t have to','could'],a:0,e:'Mustn’t diễn tả điều bị cấm. Don’t have to chỉ “không cần thiết”.'},
  {q:'Could you send me ___ updated file?',o:['a','an','the'],a:2,e:'Cả hai bên đều biết file cụ thể nào đang được nói tới, dùng “the”.'},
  {q:'If she ___ early, we will start at nine.',o:['will arrive','arrives','arrived'],a:1,e:'Mệnh đề if loại 1 dùng hiện tại đơn, không dùng will.'},
  {q:'The invoice ___ yesterday.',o:['sent','was sent','is send'],a:1,e:'Bị động quá khứ: was/were + V3.'},
  {q:'If I had more confidence, I ___ speak up in meetings.',o:['will','would','can'],a:1,e:'Điều kiện loại 2: If + quá khứ, would + động từ nguyên mẫu.'},
  {q:'She ___ English for two hours, and she is still studying.',o:['studies','has been studying','had studied'],a:1,e:'Hoạt động bắt đầu trước đây, vẫn tiếp tục và nhấn mạnh thời lượng: has been + V-ing.'},
  {q:'By the time we arrived, the meeting ___.',o:['started','has started','had started'],a:2,e:'Cuộc họp bắt đầu trước một hành động quá khứ khác, nên dùng quá khứ hoàn thành: had + V3.'},
  {q:'The ground was wet because it ___ all night.',o:['had been raining','was raining','has rained'],a:0,e:'Mưa kéo dài trước một kết quả trong quá khứ. Dùng had been + V-ing để nhấn mạnh quá trình.'},
  {q:'At 9 a.m. tomorrow, I ___ the new employees.',o:['train','will be training','will have trained'],a:1,e:'Hành động sẽ đang diễn ra tại một thời điểm cụ thể trong tương lai: will be + V-ing.'},
  {q:'We ___ the project by next Friday.',o:['will complete','will have completed','will be completing'],a:1,e:'“By next Friday” là hạn hoàn tất trong tương lai, nên dùng will have + V3.'},
  {q:'By December, he ___ at the company for ten years.',o:['will work','will have worked','will have been working'],a:2,e:'Nhấn mạnh thời lượng của hoạt động kéo dài tới một mốc tương lai: will have been + V-ing.'}
];

const saved = JSON.parse(localStorage.getItem('lingoProgress') || '{}');
const progress = {minutes:saved.minutes || 32,best:saved.best || 0,attempts:saved.attempts || 0,correct:saved.correct || 0,streak:saved.streak || 4,completed:saved.completed || [],history:saved.history || []};
const state = {topic:'present-tenses',question:0,score:0,answered:false};
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
function save(){localStorage.setItem('lingoProgress',JSON.stringify(progress));updateUI();}
function go(name){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+name+'View').classList.add('active');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===name));$('#sidebar').classList.remove('open');scrollTo({top:0,behavior:'smooth'});if(name==='library')renderLibrary();if(name==='progress')renderProgress();}
$$('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=e=>{e.preventDefault();go(b.dataset.go)});$('#menuButton').onclick=()=>$('#sidebar').classList.toggle('open');
function renderLibrary(){const done=progress.completed.length;$('#libraryCount').textContent=done;$('#libraryDone').textContent=Math.round(done/topics.length*100)+'%';$('#libraryBar').style.width=(done/topics.length*100)+'%';$('#topicGrid').innerHTML=topics.map((t,i)=>`<button class="topic-card ${t.color}" data-topic="${t.id}"><span class="topic-number">${t.icon}</span><span class="topic-status">${progress.completed.includes(t.id)?'✓ ĐÃ HỌC':t.level}</span><h3>${t.title}</h3><p>${t.desc}</p><footer><span>◷ ${t.time} phút</span><b>Học ngay →</b></footer></button>`).join('');bindTopics();}
function bindTopics(){$$('[data-topic]').forEach(b=>b.onclick=()=>openTopic(b.dataset.topic));}
function openTopic(id){state.topic=id;renderGrammar();go('grammar');}
function renderGrammar(){const t=topics.find(x=>x.id===state.topic);$('#grammarContent').innerHTML=`<header class="grammar-header"><div><span class="level-tag dark">${t.level} · CHỦ ĐIỂM ${t.icon}</span><h1>${t.title}</h1><p>${t.intro}</p></div><div class="lesson-time"><b>${t.time}</b><span>phút học</span></div></header><div class="grammar-layout"><article class="lesson-main"><section><div class="block-title"><span>01</span><div><small>NỀN TẢNG</small><h2>Công thức cần nhớ</h2></div></div><div class="formula-grid">${t.formulas.map(f=>`<div><small>${f[0]}</small><code>${f[1]}</code><p>${f[2]}</p><button class="speak" data-speak="${f[2]}">♪ Nghe câu</button></div>`).join('')}</div></section><section><div class="block-title"><span>02</span><div><small>NGỮ CẢNH</small><h2>Khi nào sử dụng?</h2></div></div><div class="use-list">${t.uses.map((u,i)=>`<div><b>${i+1}</b><p><strong>${u[0]}</strong>${u[1]}</p></div>`).join('')}</div></section><section><div class="block-title"><span>03</span><div><small>TRÁNH NHẦM</small><h2>Lỗi người Việt hay gặp</h2></div></div><div class="mistake-box"><div class="wrong"><small>SAI</small><del>${t.mistake[0]}</del></div><span>→</span><div class="right"><small>ĐÚNG</small><strong>${t.mistake[1]}</strong></div><p>${t.mistake[2]}</p></div></section></article><aside class="lesson-aside"><div class="aside-card"><p class="eyebrow">DẤU HIỆU NHẬN BIẾT</p><div class="signal-list">${t.signals.map(s=>`<span>${s}</span>`).join('')}</div></div><div class="aside-card note"><span>✦</span><h3>Học bằng ngữ cảnh</h3><p>Đừng chỉ nhớ công thức. Hãy đọc to ví dụ và thay chủ ngữ bằng thông tin của bạn.</p></div><button class="primary-button full" id="completeLesson">${progress.completed.includes(t.id)?'Ôn lại bằng bài tập':'Hoàn thành bài học'} →</button></aside></div>`;
  $$('.speak').forEach(b=>b.onclick=()=>speak(b.dataset.speak));$('#completeLesson').onclick=()=>completeTopic(t);
}
function completeTopic(t){if(!progress.completed.includes(t.id)){progress.completed.push(t.id);progress.minutes+=t.time;progress.history.unshift({title:t.title,detail:`Hoàn thành bài học · ${t.time} phút`,date:new Date().toLocaleDateString('vi-VN')});save();toast('Đã hoàn thành bài học! +'+t.time+' phút');}go('practice');}
function speak(text){if(!('speechSynthesis' in window))return toast('Trình duyệt chưa hỗ trợ phát âm.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.82;speechSynthesis.speak(u);}
$$('[data-start-quiz]').forEach(b=>b.onclick=()=>{go('practice');startQuiz()});$('#startQuiz').onclick=startQuiz;
function startQuiz(){state.question=0;state.score=0;state.answered=false;$('#quizIntro').classList.add('hidden');$('#resultArea').classList.add('hidden');$('#quizArea').classList.remove('hidden');renderQuestion();}
function renderQuestion(){const q=questions[state.question];state.answered=false;$('#quizArea').innerHTML=`<div class="quiz-progress"><div><i style="width:${state.question/questions.length*100}%"></i></div><span>${state.question+1} / ${questions.length}</span></div><p class="eyebrow">CHỌN ĐÁP ÁN ĐÚNG</p><h2>${q.q}</h2><div class="answers">${q.o.map((x,i)=>`<button data-answer="${i}"><b>${String.fromCharCode(65+i)}</b><span>${x}</span></button>`).join('')}</div><div id="feedback"></div>`;$$('[data-answer]').forEach(b=>b.onclick=()=>answer(+b.dataset.answer));}
function answer(choice){if(state.answered)return;state.answered=true;const q=questions[state.question],ok=choice===q.a;if(ok)state.score++;$$('[data-answer]').forEach((b,i)=>{b.disabled=true;if(i===q.a)b.classList.add('correct');if(i===choice&&!ok)b.classList.add('wrong')});$('#feedback').innerHTML=`<div class="feedback ${ok?'ok':'no'}"><strong>${ok?'Chính xác!':'Chưa đúng — đáp án '+String.fromCharCode(65+q.a)}</strong><p>${q.e}</p></div><button class="primary-button quiz-next" id="nextQuestion">${state.question===questions.length-1?'Xem kết quả':'Câu tiếp theo →'}</button>`;$('#nextQuestion').onclick=()=>{if(++state.question<questions.length)renderQuestion();else showResult()};}
function showResult(){const pct=Math.round(state.score/questions.length*100);progress.attempts+=questions.length;progress.correct+=state.score;progress.best=Math.max(progress.best,pct);progress.minutes+=10;progress.history.unshift({title:'Bài kiểm tra tổng hợp',detail:`${state.score}/${questions.length} câu đúng · 10 phút`,date:new Date().toLocaleDateString('vi-VN')});save();$('#quizArea').classList.add('hidden');$('#resultArea').classList.remove('hidden');$('#resultArea').innerHTML=`<div class="score-ring" style="--score:${pct*3.6}deg"><strong>${pct}</strong><small>/ 100</small></div><p class="eyebrow">KẾT QUẢ CỦA BẠN</p><h2>${pct>=80?'Rất tốt!':pct>=60?'Đang tiến bộ!':'Cùng ôn lại nhé!'}</h2><p>Bạn trả lời đúng ${state.score}/${questions.length} câu. ${pct>=80?'Bạn đã nắm khá chắc các chủ điểm cốt lõi.':'Xem lại phần giải thích và thử lại để củng cố kiến thức.'}</p><div class="result-actions"><button class="secondary-button" id="retry">Làm lại</button><button class="primary-button" id="review">Xem lộ trình →</button></div>`;$('#retry').onclick=startQuiz;$('#review').onclick=()=>go('library');}
function renderProgress(){const accuracy=progress.attempts?Math.round(progress.correct/progress.attempts*100):0;$('#masteryList').innerHTML=topics.map(t=>{const done=progress.completed.includes(t.id),v=done?100:0;return `<div class="mastery-row"><span>${t.icon}</span><div><strong>${t.title}</strong><div><i style="width:${v}%"></i></div></div><b>${done?'100%':'0%'}</b></div>`}).join('');$('#historyList').innerHTML=progress.history.length?progress.history.slice(0,6).map(h=>`<div class="history-item"><span>✓</span><div><strong>${h.title}</strong><small>${h.detail}</small></div><time>${h.date}</time></div>`).join(''):'<p class="empty-history">Hoàn thành một bài học để bắt đầu ghi lại hành trình.</p>';}
function updateUI(){$$('[data-streak]').forEach(x=>x.textContent=progress.streak);$('#homeCompleted').textContent=`${progress.completed.length} / ${topics.length}`;$('#homeMinutes').textContent=progress.minutes+' phút';$('#homeAccuracy').textContent=progress.attempts?Math.round(progress.correct/progress.attempts*100)+'%':'—';$('#totalMinutes').textContent=progress.minutes+' phút';$('#bestScore').textContent=progress.best?progress.best+'/100':'—';}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function filterLevel(button){const level=button.textContent.trim();$$('.level-switch button').forEach(b=>b.classList.toggle('active',b===button));$$('#topicGrid .topic-card').forEach(card=>{const topic=topics.find(t=>t.id===card.dataset.topic);card.style.display=level==='Tất cả'||topic.level===level?'block':'none'});}
$$('.level-switch button').forEach(button=>button.onclick=()=>filterLevel(button));
document.addEventListener('click',event=>{if(innerWidth<=900&&!$('#sidebar').contains(event.target)&&!$('#menuButton').contains(event.target))$('#sidebar').classList.remove('open')});
const hour=new Date().getHours();$('#todayLabel').textContent=hour<12?'KHỞI ĐỘNG BUỔI SÁNG':hour<18?'TIẾP TỤC TIẾN BỘ':'ÔN TẬP BUỔI TỐI';bindTopics();renderLibrary();renderGrammar();updateUI();

const chatPanel=$('#chatPanel'),chatMessages=$('#chatMessages'),chatInput=$('#chatInput');
const openChat=()=>{chatPanel.classList.add('open');chatPanel.setAttribute('aria-hidden','false');setTimeout(()=>chatInput.focus(),250)};
const closeChat=()=>{chatPanel.classList.remove('open');chatPanel.setAttribute('aria-hidden','true');$('#chatToggle').focus()};
$('#chatToggle').onclick=openChat;
$('#chatClose').onclick=closeChat;
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&chatPanel.classList.contains('open'))closeChat()});
function chatAnswer(question){const q=question.toLowerCase();
  if(q.includes('hiện tại hoàn thành tiếp diễn'))return '<b>Hiện tại hoàn thành tiếp diễn</b>: have/has been + V-ing. Dùng để nhấn mạnh quá trình bắt đầu trong quá khứ và còn tiếp tục hoặc vừa dừng nhưng còn dấu hiệu. Ví dụ: “I have been studying for two hours.”';
  if(q.includes('quá khứ hoàn thành tiếp diễn'))return '<b>Quá khứ hoàn thành tiếp diễn</b>: had been + V-ing. Dùng cho quá trình kéo dài trước một mốc quá khứ. Ví dụ: “The road was wet because it had been raining.”';
  if(q.includes('quá khứ hoàn thành'))return '<b>Quá khứ hoàn thành</b>: had + V3. Trong hai hành động quá khứ, thì này đánh dấu việc xảy ra trước. Ví dụ: “The train had left before we arrived.”';
  if(q.includes('tương lai hoàn thành tiếp diễn'))return '<b>Tương lai hoàn thành tiếp diễn</b>: will have been + V-ing. Dùng để nhấn mạnh một hoạt động sẽ kéo dài bao lâu tới mốc tương lai.';
  if(q.includes('tương lai hoàn thành'))return '<b>Tương lai hoàn thành</b>: will have + V3. Dùng cho việc sẽ hoàn tất trước một hạn tương lai, thường đi với <b>by</b> hoặc <b>by the time</b>.';
  if(q.includes('tương lai tiếp diễn'))return '<b>Tương lai tiếp diễn</b>: will be + V-ing. Dùng cho việc sẽ đang diễn ra tại một thời điểm tương lai. Ví dụ: “At 9 tomorrow, I will be working.”';
  if(q.includes('will')||q.includes('going to'))return '<b>Will</b> dùng cho quyết định ngay lúc nói, lời hứa hoặc dự đoán mang tính ý kiến. <b>Be going to</b> dùng cho dự định có từ trước hoặc dự đoán có bằng chứng.<br><br>Ví dụ: “I’ll answer the phone.” / “Look at the clouds! It’s going to rain.”';
  if(q.includes('hoàn thành')||q.includes('present perfect')||q.includes('since')||q.includes('for'))return 'Hiện tại hoàn thành có công thức <b>have/has + V3</b>. Dùng cho trải nghiệm, kết quả còn liên quan đến hiện tại, hoặc việc bắt đầu trong quá khứ và còn tiếp tục. <b>Since</b> + mốc thời gian; <b>for</b> + khoảng thời gian.';
  if(q.includes('hiện tại đơn')||q.includes('hiện tại tiếp diễn'))return '<b>Hiện tại đơn</b> diễn tả thói quen hoặc sự thật: “I work every day.” <b>Hiện tại tiếp diễn</b> diễn tả việc đang xảy ra hoặc tạm thời: “I am working now.”';
  if(q.includes('quá khứ'))return 'Quá khứ đơn kể hành động đã hoàn tất: <b>S + V2/ed</b>. Quá khứ tiếp diễn tạo bối cảnh đang xảy ra: <b>S + was/were + V-ing</b>. Ví dụ: “I was driving when she called.”';
  if(q.includes('mạo từ')||q.includes(' a ')||q.includes(' an ')||q.includes(' the '))return '<b>A/an</b> dùng khi nhắc một danh từ đếm được số ít lần đầu. <b>The</b> dùng khi đối tượng đã xác định hoặc cả hai bên đều biết. Chọn a/an theo <i>âm</i>: “an hour” nhưng “a university”.';
  if(q.includes('điều kiện')||q.includes(' if '))return 'Có 3 loại chính: loại 0 cho sự thật; loại 1 cho khả năng có thật; loại 2 cho giả định. Lưu ý: mệnh đề <b>if</b> loại 1 dùng hiện tại đơn, không dùng “will”.';
  if(q.includes('modal')||q.includes('should')||q.includes('must')||q.includes('can '))return 'Sau modal verbs như can, could, should, must luôn dùng <b>động từ nguyên mẫu không “to”</b>. Mustn’t nghĩa là “bị cấm”; don’t have to nghĩa là “không cần thiết”.';
  if(q.includes('bị động')||q.includes('passive'))return 'Câu bị động có cấu trúc <b>S + be + V3</b>. Ví dụ: “The email was sent yesterday.” Dùng khi tác nhân không rõ, không quan trọng hoặc muốn nhấn mạnh kết quả.';
  return 'Mình chưa hiểu trọn câu hỏi này. Minh thử hỏi theo một chủ điểm cụ thể như <b>các thì, mạo từ, modal verbs, câu điều kiện</b> hoặc <b>câu bị động</b> nhé.';
}
function sendChat(text){const value=text.trim();if(!value)return;chatMessages.insertAdjacentHTML('beforeend',`<div class="chat-message user"><p>${value.replace(/[<>]/g,'')}</p></div>`);chatInput.value='';chatMessages.scrollTop=chatMessages.scrollHeight;setTimeout(()=>{chatMessages.insertAdjacentHTML('beforeend',`<div class="chat-message bot"><span>L</span><p>${chatAnswer(value)}</p></div>`);chatMessages.scrollTop=chatMessages.scrollHeight},350)}
$('#chatForm').onsubmit=e=>{e.preventDefault();sendChat(chatInput.value)};
$$('.chat-suggestions button').forEach(button=>button.onclick=()=>sendChat(button.textContent));
